version: '3.9'

services:

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb:/var/run/mysqld
    env_file :
      - .env
    expose:
      - "3306"
    networks : 
      - inception
    restart : on-failure


  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    env_file :
      - .env
    expose:
      - "9000"
    networks : 
      - inception
    restart : on-failure
    

    
  nginx:
    depends_on:
      - wordpress
    image: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    env_file :
      - .env
    ports:
      - "443:443"
    networks :
      - inception
    restart : on-failure
 
volumes:

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress

networks:
  inception :
    driver : bridge