version: '3'

services:
  nginx:
    build:
      context: ./srcs/requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./srcs/requirements/nginx/conf/:/etc/nginx/conf.d/
      - ./srcs/requirements/nginx/tools:/etc/nginx/ssl/
      # - /home/ykhalil-/simple_docker_nginx_html/public/html:/var/www/
    restart: always
